#!/bin/bash

set -e

usage() {
    echo "Usage: $0 [--since <date> | --latest] [--help]"
    echo
    echo "Command options:"
    echo "  --since <date>   Specify the start date for the changelog (default: 2005-01-01)."
    echo "  --latest         Generate changelog for commits executed in the latest software version. When used, --since is ignored."
    exit 0
}

# Default values
SINCE="2005-01-01"
LATEST=false

# Parse optional arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --since)
            if [[ -n $2 && $2 != -* ]]; then
                SINCE=$2
                shift 2
            else
                echo "Option --since requires an argument."
                exit 1
            fi
            ;;
        --latest)
            LATEST=true
            shift
            ;;
        --help)
            usage
            ;;
        -*)
            echo "Invalid option: $1"
            exit 1
            ;;
        *)
            echo "Invalid argument: $1"
            exit 1
            ;;
    esac
done

# Updating project silently
git remote update > /dev/null

# Get basename
repository_name=$(basename `git rev-parse --show-toplevel`)
file_suffix="_changelog.md"

file_name="$repository_name$file_suffix"
echo "Generating changlog with name: $file_name"

if repository_version=$(git describe --tags --abbrev=0 2>/dev/null); then
    echo "Latest version found: $repository_version"
else
    repository_version="0.1"
    echo "No tags found, using default: $repository_version"
fi

latest_version_creation=$(git for-each-ref --sort=-creatordate --format '%(creatordate)' refs/tags | head -n 1)

# Setting up file title
echo "# $repository_name $repository_version
All notable changes to this project will be documented in this file. The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) and this project adheres to [Semantic Versioning](https://semver.org/).
" > "$file_name"

if [[ "$LATEST" == true ]]; then
    SINCE=$latest_version_creation
    echo "Reading logs of latest version only"
fi

if [ "$LATEST" = true ]; then
    echo "## Change Log
Showing changes made in $repository_version
" >> "$file_name"
else
    echo "## Change Log
Showing changes from $SINCE
" >> "$file_name"
fi

all_messages=$(git log --oneline --format='%B' --since="$SINCE")
features=$(echo "$all_messages" | grep 'feat')

echo "### Features
$features" | sed -e 's/feat[ure]\?!\?\((.*)\)\? \?:/-/g' | uniq >> "$file_name"

bugfixes=$(echo "$all_messages" | grep 'fix')

echo "
### Bugfixes
$bugfixes" | sed -e 's/\(fix\|refactor\)!\?\((.*)\)\? \?:/-/g' | uniq >> "$file_name"